name: my_tcp

services:
  tcp:
    image: gcc:14.3.0-bookworm
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: >
      sh -c "make && ./bin/my_tcp && echo 'Done!'"
